name: Update ELGhazi Data
on:
  repository_dispatch:
    types: [update-json]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Write JSON Data
        run: |
          echo '${{ github.event.client_payload.content }}' > data/${{ github.event.client_payload.filename }}.json
      - name: Commit and Push
        run: |
          git config user.name "ELGhazi-Bot"
          git config user.email "bot@elghazi.com"
          git add .
          git commit -m "تحديث تلقائي للمحتوى من لوحة التحكم"
          git push
